# Generated by Django 4.1.2 on 2022-10-29 14:15

from django.db import migrations
# import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments_comments_blog_commen_created_ad0231_idx'),
    ]

    operations = [
    #     migrations.AlterField(
    #         model_name='post',
    #         name='body',
    #         field=django_quill.fields.QuillField(default='ici'),
    #     ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
