# Generated by Django 4.1.3 on 2022-11-12 23:28

from django.db import migrations
# import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_tags'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='post',
        #     name='body',
        #     # field=django_quill.fields.QuillField(),
        # ),
    ]
